#-*- coding: UTF-8 -*-
# unicode_literals 把所有的字符串转成unicode
from __future__ import unicode_literals
import os,re,sys

# 设置默认编码是utf-8，不然处理不了中文
reload(sys)
sys.setdefaultencoding('utf-8')

from database import *
path = '../static/music/'
image_path = '../static/images/music_pictures/'
music_list = [
    dict(
        music_name = '光辉岁月',
        music_publish_date = '1991/05/09',
        music_url = path +'光辉岁月.mp3',
        music_artist = 'beyond',
        music_zone = 'HK',
        music_style = 'rock',
        music_mood = 'Happy',
        music_picture_url = image_path + 'beyond.jpg'
    ),
    dict(
        music_name = '千千阙歌',
        music_publish_date = '2013/05/09',
        music_url = path +'千千阙歌.mp3',
        music_artist = '梅艳芳',
        music_zone = 'HK',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '梅艳芳.jpg'
    ),
    dict(
        music_name = 'Stay Beautiful',
        music_publish_date = '2014/05/03',
        music_url = path +'Stay Beautiful.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'USA',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift1.jpg',
    ),
    dict(
        music_name = '浮夸',
        music_publish_date = '2013/06/10',
        music_url = path +'浮夸.mp3',
        music_artist = '陈奕迅',
        music_zone = 'HK',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '陈奕迅2.jpg',
    ),
    dict(
        music_name = 'K歌之王',
        music_publish_date = '2013/08/15',
        music_url = path +'K歌之王.mp3',
        music_artist = '陈奕迅',
        music_zone = 'HK',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '陈奕迅1.jpg',
    ),
    dict(
        music_name = '十年',
        music_publish_date = '2013/04/20',
        music_url = path +'十年.mp3',
        music_artist = '陈奕迅',
        music_zone = 'HK',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '陈奕迅3.jpg',
    ),
    dict(
        music_name = '红豆',
        music_publish_date = '2012/01/12',
        music_url = path +'红豆.mp3',
        music_artist = '王菲',
        music_zone = 'HKTW',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '王菲1.jpg',
    ),
    dict(
        music_name = '传奇',
        music_publish_date = '2010/09/15',
        music_url = path +'传奇.mp3',
        music_artist = '王菲',
        music_zone = 'HKTW',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '王菲2.jpg',
    ),
    dict(
        music_name = '我愿意',
        music_publish_date = '2013/07/20',
        music_url = path +'我愿意.mp3',
        music_artist = '王菲',
        music_zone = 'HKTW',
        music_style = 'Classical',
        music_mood = 'Happy',
        music_picture_url = image_path + '王菲3.jpg',
    ),
    dict(
        music_name = '因为爱情',
        music_publish_date = '2014/03/24',
        music_url = path +'因为爱情.mp3',
        music_artist = '王菲',
        music_zone = 'HKTW',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '王菲4.jpg',
    ),
    dict(
        music_name = '但愿人长久',
        music_publish_date = '2010/08/19',
        music_url = path +'但愿人长久.mp3',
        music_artist = '王菲',
        music_zone = 'HKTW',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '王菲5.jpg',
    ),
    dict(
        music_name = '青花瓷',
        music_publish_date = '2014/03/10',
        music_url = path +'青花瓷.mp3',
        music_artist = '周杰伦',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '周杰伦1.jpg',
    ),
    dict(
        music_name = '发如雪',
        music_publish_date = '2012/09/10',
        music_url = path +'发如雪.mp3',
        music_artist = '周杰伦',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '周杰伦2.jpg',
    ),
    dict(
        music_name = '一路向北',
        music_publish_date = '2013/01/16',
        music_url = path +'一路向北.mp3',
        music_artist = '周杰伦',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '周杰伦3.jpg',
    ),
    dict(
        music_name = '回到过去',
        music_publish_date = '2013/04/10',
        music_url = path +'回到过去.mp3',
        music_artist = '周杰伦',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '周杰伦4.jpg',
    ),
    dict(
        music_name = '东风破',
        music_publish_date = '2012/09/20',
        music_url = path +'东风破.mp3',
        music_artist = '周杰伦',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '周杰伦5.jpg',
    ),
    dict(
        music_name = '大海',
        music_publish_date = '1992/12/10',
        music_url = path +'大海.mp3',
        music_artist = '张雨生',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '大海.jpg',
    ),
    dict(
        music_name = '我的未来不是梦',
        music_publish_date = '1990/08/10',
        music_url = path +'我的未来不是梦.mp3',
        music_artist = '张雨生',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Happy',
        music_picture_url = image_path + '张雨生1.jpg',
    ),
    dict(
        music_name = '我期待',
        music_publish_date = '1991/11/20',
        music_url = path +'我期待.mp3',
        music_artist = '张雨生',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Happy',
        music_picture_url = image_path + '张雨生1.jpg',
    ),
    dict(
        music_name = '口是心非',
        music_publish_date = '1993/04/10',
        music_url = path +'口是心非.mp3',
        music_artist = '张雨生',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '口是心非.jpg',
    ),
    dict(
        music_name = '我是一颗秋天的树',
        music_publish_date = '1994/07/21',
        music_url = path +'我是一颗秋天的树.mp3',
        music_artist = '张雨生',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '我是一颗秋天的树.jpg',
    ),
    dict(
        music_name = ' I Knew You Were Trouble',
        music_publish_date = '2013/11/22',
        music_url = path +'I Knew You Were Trouble.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift1.jpg',
    ),
    dict(
        music_name = 'You Belong With Me',
        music_publish_date = '2014/01/21',
        music_url = path +'You Belong With Me.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift2.jpg',
    ),
    dict(
        music_name = 'We Are Never Ever Getting Back Together',
        music_publish_date = '2011/10/11',
        music_url = path +'We Are Never Ever Getting Back Together.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift3.jpg',
    ),
    dict(
        music_name = 'Last Christmas',
        music_publish_date = '2011/09/16',
        music_url = path +'Last Christmas.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift4.jpg',
    ),
    dict(
        music_name = 'Red',
        music_publish_date = '2013/06/15',
        music_url = path +'Red.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift5.jpg',
    ),
    dict(
        music_name = 'Love Story',
        music_publish_date = '2013/04/20',
        music_url = path +'Love Story.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift6.jpg',
    ),
    dict(
        music_name = 'Cold As You',
        music_publish_date = '2014/05/10',
        music_url = path +'Cold As You.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'ColdAsYou.jpg',
    ),
    dict(
        music_name = 'Sparks Fly',
        music_publish_date = '2012/09/20',
        music_url = path +'Sparks Fly.mp3',
        music_artist = 'yxjxx'   ,
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'SparksFly.jpg',
    ),
    dict(
        music_name = 'Back To December',
        music_publish_date = '2013/03/12',
        music_url = path +'Back To December.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift3.jpg',
    ),
    dict(
        music_name = 'Never Grow Up',
        music_publish_date = '2013/12/20',
        music_url = path +'Never Grow Up.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift4.jpg',
    ),
    dict(
        music_name = 'Speak Now',
        music_publish_date = '2013/08/18',
        music_url = path +'Speak Now.mp3',
        music_artist = 'Taylor Swift',
        music_zone = 'EU',
        music_style = 'folk',
        music_mood = 'Happy',
        music_picture_url = image_path + 'TaylorSwift5.jpg',
    ),
    dict(
        music_name = 'My Heart Will Go On',
        music_publish_date = '2010/06/12',
        music_url = path +'My Heart Will Go On.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'When I Fall In Love',
        music_publish_date = '2010/04/10',
        music_url = path +'When I Fall In Love.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Show Some Emotion',
        music_publish_date = '2011/05/21',
        music_url = path +'Show Some Emotion.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'The Power Of The Dream',
        music_publish_date = '2010/09/26',
        music_url = path +'The Power Of The Dream.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Beauty And The Beast',
        music_publish_date = '2011/07/07',
        music_url = path +'Beauty And The Beast.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'If You Asked Me To',
        music_publish_date = '2011/10/21',
        music_url = path +'If You Asked Me To.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'I Love You Goodbye',
        music_publish_date = '2011/11/22',
        music_url = path +'I Love You Goodbye.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Water From The Moon',
        music_publish_date = '2012/01/11',
        music_url = path +'Water From The Moon.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Because You Loved Me ',
        music_publish_date = '2012/06/24',
        music_url = path +'Because You Loved Me.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'If I Were You',
        music_publish_date = '2012/03/19',
        music_url = path +'If I Were You.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Nothing Broken But My Heart',
        music_publish_date = '2012/07/24',
        music_url = path +'Nothing Broken But My Heart.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Love Can Move Mountains',
        music_publish_date = '2013/09/21',
        music_url = path +'Love Can Move Mountains.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'With This Tear',
        music_publish_date = '2014/04/20',
        music_url = path +'With This Tear.mp3',
        music_artist = 'Celine Dion',
        music_zone = 'EU',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Mr.Mr.',
        music_publish_date = '2014/05/20',
        music_url = path +'Mr.Mr..mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Sunflower',
        music_publish_date = '2013/09/20',
        music_url = path +'Sunflower.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'MR TAXI',
        music_publish_date = '2012/03/11',
        music_url = path +'MR TAXI.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'The Boys',
        music_publish_date = '2011/11/20',
        music_url = path +'The Boys.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Gee',
        music_publish_date = '2011/07/24',
        music_url = path +'Gee.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'I Got A Boy',
        music_publish_date = '2011/05/23',
        music_url = path +'I Got A Boy.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Goodbye',
        music_publish_date = '2010/12/20',
        music_url = path +'Goodbye.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Soul',
        music_publish_date = '2010/11/21',
        music_url = path +'Soul.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Genie',
        music_publish_date = '2010/09/20',
        music_url = path +'Genie.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Europa',
        music_publish_date = '2010/06/15',
        music_url = path +'Europa.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Dancing Queen',
        music_publish_date = '2010/04/20',
        music_url = path +'Dancing Queen.mp3',
        music_artist = '少女时代',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Answer',
        music_publish_date = '2010/03/23',
        music_url = path +'Answer.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Bolero',
        music_publish_date = '2010/04/10',
        music_url = path +'Bolero.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Catch Me',
        music_publish_date = '2010/07/25',
        music_url = path +'Catch Me.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Forever Love',
        music_publish_date = '',
        music_url = path +'Forever Love.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Hug',
        music_publish_date = '2011/06/20',
        music_url = path +'Hug.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Keep Your Head Down',
        music_publish_date = '2011/09/12',
        music_url = path +'Keep Your Head Down.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Love In The Ice',
        music_publish_date = '2012/04/20',
        music_url = path +'Love In The Ice.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Purple Line',
        music_publish_date = '2012/06/21',
        music_url = path +'Purple Line.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Rising Sun',
        music_publish_date = '2013/04/28',
        music_url = path +'Rising Sun.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '傻瓜',
        music_publish_date = '2013/09/23',
        music_url = path +'傻瓜.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '咒文',
        music_publish_date = '2014/05/20',
        music_url = path +'咒文.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '我相信',
        music_publish_date = '2014/01/10',
        music_url = path +'我相信.mp3',
        music_artist = '东方神起',
        music_zone = 'Korea',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'My All',
        music_publish_date = '2010/01/20',
        music_url = path +'My All.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Heaven',
        music_publish_date = '2010/04/11',
        music_url = path +'Heaven.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Dearest',
        music_publish_date = '2010/07/21',
        music_url = path +'Dearest.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Jewel',
        music_publish_date = '2011/06/14',
        music_url = path +'Jewel.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Rainbow',
        music_publish_date = '2011/10/11',
        music_url = path +'Rainbow.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Secret',
        music_publish_date = '2012/08/10',
        music_url = path +'Secret.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Rainy Day',
        music_publish_date = '2012/12/20',
        music_url = path +'Rainy Day.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Momentum',
        music_publish_date = '2013/05/07',
        music_url = path +'Momentum.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'No Way To Say',
        music_publish_date = '2014/02/14',
        music_url = path +'No Way To Say.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'End Roll',
        music_publish_date = '2014/05/13',
        music_url = path +'End Roll.mp3',
        music_artist = '滨崎步',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'First Love',
        music_publish_date = '2004/03/31',
        music_url = path +'First Love.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'For You',
        music_publish_date = '2004/03/31',
        music_url = path +'For You.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Letters',
        music_publish_date = '2004/03/31',
        music_url = path +'Letters.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Traveling',
        music_publish_date = '2004/03/31',
        music_url = path +'Traveling.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Colors',
        music_publish_date = '2004/03/31',
        music_url = path +'Colors.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Automatic',
        music_publish_date = '2004/03/31',
        music_url = path +'Automatic.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'In My Room',
        music_publish_date = '1999/11/10',
        music_url = path +'In My Room.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Never Let Go',
        music_publish_date = '1999/11/10',
        music_url = path +'Never Let Go.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = 'Give Me A Reason',
        music_publish_date = '2004/03/31',
        music_url = path +'Give Me A Reason.mp3',
        music_artist = '宇多田光',
        music_zone = 'Japan',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '你是我的眼',
        music_publish_date = '2010/10/21',
        music_url = path +'你是我的眼.mp3',
        music_artist = '林宥嘉',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '夕阳之歌',
        music_publish_date = '19960/06/15',
        music_url = path +'夕阳之歌.mp3',
        music_artist = '梅艳芳',
        music_zone = 'HKTW',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '千千阙歌',
        music_publish_date = '1990/06/15',
        music_url = path +'千千阙歌.mp3',
        music_artist = '梅艳芳',
        music_zone = 'HKTW',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '逍遥叹',
        music_publish_date = '2011/03/20',
        music_url = path +'逍遥叹.mp3',
        music_artist = '胡歌',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '天仙子',
        music_publish_date = '2004/09/20',
        music_url = path +'天仙子.mp3',
        music_artist = '谢雨欣',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '留香',
        music_publish_date = '2011/01/20',
        music_url = path +'留香.mp3',
        music_artist = '吴奇隆',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '一眼万年',
        music_publish_date = '2008/09/21',
        music_url = path +'一眼万年',
        music_artist = 'S.H.E',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '相忘于江湖',
        music_publish_date = '2010/04/15',
        music_url = path +'相忘于江湖',
        music_artist = '陈楚生',
        music_zone = 'China',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '最浪漫的事',
        music_publish_date = '2003/01/08',
        music_url = path +'最浪漫的事.mp3',
        music_artist = '赵咏华',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '爱不释手',
        music_publish_date = '2004/12/12',
        music_url = path +'爱不释手.mp3',
        music_artist = '李丽芬',
        music_zone = 'China',
        music_style = 'Classical',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '月亮代表我的心',
        music_publish_date = '1989/03/24',
        music_url = path +'月亮代表我的心.mp3',
        music_artist = '邓丽君',
        music_zone = 'HKTW',
        music_style = 'Classical',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '海阔天空',
        music_publish_date = '2000/09/15',
        music_url = path +'海阔天空.mp3',
        music_artist = '黄家驹',
        music_zone = 'HKTW',
        music_style = 'POP',
        music_mood = 'Happy',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '大地',
        music_publish_date = '2000/03/27',
        music_url = path +'大地.mp3',
        music_artist = '黄家驹',
        music_zone = 'HKTW',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
    dict(
        music_name = '冷雨夜',
        music_publish_date = '2001/01/20',
        music_url = path +'冷雨夜.mp3',
        music_artist = '黄家驹',
        music_zone = 'HKTW',
        music_style = 'POP',
        music_mood = 'Sad',
        music_picture_url = image_path + '.jpg',
    ),
]

for music in music_list:
    if not music.get('music_picture_url'):
        music['music_picture_url'] = image_path + 'default.jpg'
    insert_music_to_database(music)
    # print(music)
print("OK")
